// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Boot() {
  return window['go']['main']['App']['Boot']();
}

export function BuildPresentation(arg1) {
  return window['go']['main']['App']['BuildPresentation'](arg1);
}

export function ChooseMarkdownRootDirectory() {
  return window['go']['main']['App']['ChooseMarkdownRootDirectory']();
}

export function DeletePresentation(arg1) {
  return window['go']['main']['App']['DeletePresentation'](arg1);
}

export function ExportPresentationPDF(arg1) {
  return window['go']['main']['App']['ExportPresentationPDF'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListPresentations() {
  return window['go']['main']['App']['ListPresentations']();
}

export function OpenPresentation(arg1, arg2) {
  return window['go']['main']['App']['OpenPresentation'](arg1, arg2);
}

export function OpenPresentationFolder(arg1) {
  return window['go']['main']['App']['OpenPresentationFolder'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function RebuildPresentation(arg1) {
  return window['go']['main']['App']['RebuildPresentation'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchMarkdownFiles(arg1) {
  return window['go']['main']['App']['SearchMarkdownFiles'](arg1);
}
