// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Boot():Promise<main.BootState>;

export function BuildPresentation(arg1:string):Promise<main.BootState>;

export function ChooseMarkdownRootDirectory():Promise<string>;

export function CloseWindow():Promise<void>;

export function DeletePresentation(arg1:string):Promise<main.BootState>;

export function ExportPresentationPDF(arg1:string):Promise<string>;

export function GetAvailableBrowsers():Promise<Array<main.BrowserOption>>;

export function GetSettings():Promise<main.AppSettings>;

export function ListPresentations():Promise<Array<main.Presentation>>;

export function OpenPresentation(arg1:string,arg2:boolean):Promise<void>;

export function OpenPresentationFolder(arg1:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function RebuildPresentation(arg1:string):Promise<main.BootState>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function SearchMarkdownFiles(arg1:string):Promise<Array<main.SearchResult>>;
